apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: {{.Release.Name}}
